if("undefined"!==typeof goog)var Apiomat={Status:{}};"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Status={SCRIPT_ERROR:701,APPLICATION_NOT_ACTIVE:702,BAD_IMAGE:703,BAD_ID:704,CONCURRENT_ACCESS:705,APPLICATION_SANDBOX:706,MODEL_NOT_DEPLOYED:707,WRONG_REF_TYPE:709,ATTRIBUTE_NOT_SET:710,OPERATION_NOT_POSSIBLE:711,APPLICATION_NAME_MISMATCH:712,WRONG_AUTH_HEADER:713,MODEL_STILL_USED:714,COLLECTION_NOT_ALLOWED:715,FB_NO_VALID_MEMBER:716,FB_NO_OAUTH_TOKEN:717,FB_POST_ID_MISSING:718,RESTORE_NO_DUMPS_FOUND:719,TW_NO_VALID_MEMBER:720,TW_NO_OAUTH_TOKEN:721,IMEXPORT_WRONG_ENCODING:722,IMEXPORT_WRONG_CONTENT:723,
PUSH_PAYLOAD_EXCEEDED:724,PUSH_ERROR:725,BAD_EMAIL:726,BAD_PROMOTIONCODE_DISCOUNT:727,BAD_PROMOTIONCODE_CODE:728,PLAN_PRICE:729,PLAN_NO_SYSTEMS:730,SCRIPT_TIME_ERROR:731,INVALID_NAME:732,ATTRIBUTE_IN_SUPERCLASS:733,JSON_TYPE_ERROR:734,TBLR_NO_VALID_MEMBER:735,TBLR_NO_OAUTH_TOKEN:736,TBLR_POST_ID_MISSING:737,LOCATION_INVALID:738,SCRIPT_EXCEPTION:739,BAD_CUSTOMERNAME:740,BAD_IMAGE_ALPHA:746,BAD_IMAGE_BGCOLOR:747,BAD_IMAGE_FORMAT:748,QUERY_ERROR:708,BAD_TYPE_IN_QUERY:741,UNKNOWN_CLASS_IN_QUERY:742,WRONG_NUM_FORMAT_IN_QUERY:743,
QUERY_PARSE_ERROR:744,UNKNOWN_ATTRIBUTE_IN_QUERY:745,FOREIGNID_NOT_SET:749,CLASSES_MISSING:750,INVALID_ATTRIBUTE_TYPE:751,TOKEN_VALUE_EXISTS:752,JSON_FORMAT_ERROR:753,MODULE_DEPLOYMENT:754,BAD_USERNAME:755,CSV_ZIP_FORMAT:756,VERIFICATION:757,MODULE_STILL_USED:758,CLASS_NOT_IN_MODULE:759,ORDER_TRANSACTION_TIMESTAMP_OUTDATED:760,ORDER_TRANSACTION_ID_INVALID:761,ORDER_TRANSACTION_SECRET_INVALID:762,MANDATORY_FIELD:763,INVALID_PASSWD_LENGTH:764,BAD_PROMOTIONCODE_VALID:765,APPLICATION_NOT_FOUND:801,CUSTOMER_NOT_FOUND:802,
ID_NOT_FOUND:803,MODEL_NOT_FOUND:804,MODULE_NOT_FOUND:805,METAMODEL_NOT_FOUND:806,PLAN_NOT_FOUND:807,PROMOCODE_NOT_FOUND:808,DEMOAPP_NOT_FOUND:809,MODULE_USE_FORBIDDEN:820,PUSH_ERROR_APIKEY:821,PUSH_ERROR_CERTIFICATE:822,SAME_NAME_USED_IN_SUPERCLASS:823,PAYMENT_MAX_MODULE:824,PAYMENT_SYSTEM:825,PAYMENT_DOWNGRADE:826,SAVE_REFERENECE_BEFORE_REFERENCING:827,PAYMENT_DB_SIZE:828,ENDPOINT_PATH_NOT_ALLOWED:829,PAYMENT_NO_CRON:1820,PAYMENT_MODULE_NOT_FREE:1821,NATIVEMODULE_DEACTIVATED:1822,LICENSE_INVALID:1823,
PAYMENT_NO_CUSTOMERROLES:1824,WHITELABEL:1825,WHITELABEL_NOT:1826,MODULE_CONFIG_NO_DOT:1827,PLAN_FALLBACK:1828,PLAN_INACTIVE:1829,ID_EXISTS:830,NAME_RESERVED:831,CIRCULAR_DEPENDENCY:832,NAME_EXISTS:833,UNAUTHORIZED:840,WRONG_APIKEY:841,EVALANCHE_UNAUTH:842,PW_CHANGE_W_TOKEN:843,TOKEN_AUTH_ERROR:844,TOKEN_READ_ONLY:845,CRUD_ERROR:901,IMEXPORT_ERROR:902,COMPILE_ERROR:903,REFERENCE_ERROR:904,PUSH_PAYLOAD_ERROR:905,PUSH_SEND_ERROR:906,PUSH_INIT_FAILED:907,FACEBOOK_ERROR:908,FACEBOOK_OAUTH_ERROR:910,FACEBOOK_OAUTH_ERROR2:917,
MEMBER_NOT_FOUND:911,WORDPRESS_FETCH_DATA_ERROR:912,TUMBLR_OAUTH_ERROR:913,TUMBLR_ERROR:914,EXECUTE_METHOD_ERROR_PRIMITIVE:915,EXECUTE_METHOD_ERROR:916,OAUTH_TOKEN_REQUEST_ERROR:918,FINDING_RESOURCE_ERROR:919,NATIVEMODULE_DEPLOY:920,TOKEN_SEARCH_ERROR:921,MODULE_CONFIG_MISSING:922,HREF_NOT_FOUND:601,WRONG_URI_SYNTAX:602,WRONG_CLIENT_PROTOCOL:603,IO_EXCEPTION:604,UNSUPPORTED_ENCODING:605,INSTANTIATE_EXCEPTION:606,IN_PERSISTING_PROCESS:607,VERIFY_SOCIALMEDIA:608,TOO_MANY_LOCALIDS:609,MAX_CACHE_SIZE_REACHED:610,
CANT_WRITE_IN_CACHE:611,BAD_DATASTORE_CONFIG:612,NO_TOKEN_RECEIVED:613,NO_NETWORK:614,ID_NOT_FOUND_OFFLINE:615,ATTACHED_HREF_MISSING:616,REQUEST_TIMEOUT:617,ASYNC_WAIT_ERROR:618,IN_DELETING_PROCESS:619,SSO_REDIRECT:620,MALICIOUS_MEMBER:950,getReasonPhrase:function(c){var b=void 0;switch(c){case a.Status.SCRIPT_ERROR:b="Script error!";break;case a.Status.APPLICATION_NOT_ACTIVE:b="Application is deactivated!";break;case a.Status.BAD_IMAGE:b="Image format seems to be corrupted!";break;case a.Status.BAD_ID:b=
"ID format is wrong!";break;case a.Status.CONCURRENT_ACCESS:b="Concurrent access forbidden!";break;case a.Status.APPLICATION_SANDBOX:b="Application is in sandbox mode!";break;case a.Status.MODEL_NOT_DEPLOYED:b="Class is not deployed!";break;case a.Status.WRONG_REF_TYPE:b="Wrong reference type!";break;case a.Status.ATTRIBUTE_NOT_SET:b="Attribute not set!";break;case a.Status.OPERATION_NOT_POSSIBLE:b="CRUD operation not possible on this class!";break;case a.Status.APPLICATION_NAME_MISMATCH:b="Application name does not match the one defined in the class!";
break;case a.Status.WRONG_AUTH_HEADER:b="Wrong authentication header format, must be 'username:password'";break;case a.Status.MODEL_STILL_USED:b="Class is still used by other attributes, scripts or subclasses!'";break;case a.Status.COLLECTION_NOT_ALLOWED:b="Collection is not supported for this class type!";break;case a.Status.FB_NO_VALID_MEMBER:b="Request send from no valid member";break;case a.Status.FB_NO_OAUTH_TOKEN:b="Requesting member has no oAuth token, please authenticate! See http://doc.apiomat.com";
break;case a.Status.FB_POST_ID_MISSING:b="Facebook post id has to be set!";break;case a.Status.RESTORE_NO_DUMPS_FOUND:b="No dumps for app on this date exist!";break;case a.Status.TW_NO_VALID_MEMBER:b="Request send from no valid member";break;case a.Status.TW_NO_OAUTH_TOKEN:b="Requesting member has no oAuth token, please authenticate! See http://doc.apiomat.com";break;case a.Status.IMEXPORT_WRONG_ENCODING:b="Wrong Encoding";break;case a.Status.IMEXPORT_WRONG_CONTENT:b="Wrong Filecontent";break;case a.Status.PUSH_PAYLOAD_EXCEEDED:b=
"Payload size exceeded!";break;case a.Status.PUSH_ERROR:b="Error in push request!";break;case a.Status.BAD_EMAIL:b="eMail format is wrong!";break;case a.Status.BAD_PROMOTIONCODE_DISCOUNT:b="Discount value is wrong!";break;case a.Status.BAD_PROMOTIONCODE_CODE:b="Code is invalid";break;case a.Status.PLAN_PRICE:b="Plan price must be \x3e\x3d 0!";break;case a.Status.PLAN_NO_SYSTEMS:b="Plan must have at least one system!";break;case a.Status.SCRIPT_TIME_ERROR:b="Script was interrupted, execution took too long.";
break;case a.Status.INVALID_NAME:b="Name must start with a letter, followed only by letters or numbers.";break;case a.Status.ATTRIBUTE_IN_SUPERCLASS:b="Attribute is already defined in superclass.";break;case a.Status.JSON_TYPE_ERROR:b="The @type is not correctly defined in your JSON (must be: MODULENAME$CLASSNAME";break;case a.Status.TBLR_NO_VALID_MEMBER:b="Request send from no valid member";break;case a.Status.TBLR_NO_OAUTH_TOKEN:b="Requesting member has no oAuth token, please authenticate! See http://doc.apiomat.com";
break;case a.Status.TBLR_POST_ID_MISSING:b="Tumblr post id has to be set!";break;case a.Status.LOCATION_INVALID:b="Location data is invalid (latitude or longitude missing)!";break;case a.Status.SCRIPT_EXCEPTION:b="Exception was raised in script!";break;case a.Status.BAD_CUSTOMERNAME:b="Customer name must contain only characters A-Z,a-z or 0-9!";break;case a.Status.BAD_IMAGE_ALPHA:b="alpha is wrong (must be a double value between 0.0 and 1.0)";break;case a.Status.BAD_IMAGE_BGCOLOR:b="bgcolor is wrong (must be an RGB hex value without #, like 'FF0000' for red)";
break;case a.Status.BAD_IMAGE_FORMAT:b="format is wrong (can only be png, gif, bmp or jpg/jpeg)";break;case a.Status.QUERY_ERROR:b="Query could not be parsed!";break;case a.Status.BAD_TYPE_IN_QUERY:b="The query contains a value with the wrong type";break;case a.Status.UNKNOWN_CLASS_IN_QUERY:b="The definition of the class couldn't be found";break;case a.Status.WRONG_NUM_FORMAT_IN_QUERY:b="A number was supplied in the wrong format";break;case a.Status.QUERY_PARSE_ERROR:b="The query couldn't be parsed";
break;case a.Status.UNKNOWN_ATTRIBUTE_IN_QUERY:b="An attribute that was used in the query doesn't exist in the class";break;case a.Status.FOREIGNID_NOT_SET:b="Foreign ID must be set to a unique value for this class!";break;case a.Status.CLASSES_MISSING:b="Not all classes for this module are contained in the jar! This will lead to compile errors.";break;case a.Status.INVALID_ATTRIBUTE_TYPE:b="Attributes type is invalid";break;case a.Status.TOKEN_VALUE_EXISTS:b="The token value already exists";break;
case a.Status.JSON_FORMAT_ERROR:b="JSON could not be parsed";break;case a.Status.MODULE_DEPLOYMENT:b="Module is currently deploying. Please try again later.";break;case a.Status.BAD_USERNAME:b="User name must not contain a ':'.";break;case a.Status.CSV_ZIP_FORMAT:b="CSV import only accepts a single .zip file!";break;case a.Status.VERIFICATION:b="Verification error";break;case a.Status.MODULE_STILL_USED:b="Module is still used by other modules of this app!'";break;case a.Status.CLASS_NOT_IN_MODULE:b=
"Model name not found for this module!";break;case a.Status.ORDER_TRANSACTION_TIMESTAMP_OUTDATED:b="Transaction outdated!";break;case a.Status.ORDER_TRANSACTION_ID_INVALID:b="Transaction ID invalid!";break;case a.Status.ORDER_TRANSACTION_SECRET_INVALID:b="Transaction secret invalid!";break;case a.Status.MANDATORY_FIELD:b="Mandatory fields must not be empty or null!";break;case a.Status.INVALID_PASSWD_LENGTH:b="Password must have a length of at least 6 characters!";break;case a.Status.BAD_PROMOTIONCODE_VALID:b=
"Valid from/to of Code is null";break;case a.Status.APPLICATION_NOT_FOUND:b="Application was not found!";break;case a.Status.CUSTOMER_NOT_FOUND:b="Customer was not found!";break;case a.Status.ID_NOT_FOUND:b="ID was not found!";break;case a.Status.MODEL_NOT_FOUND:b="Class was not found!";break;case a.Status.MODULE_NOT_FOUND:b="Module was not found!";break;case a.Status.METAMODEL_NOT_FOUND:b="Meta Class was not found!";break;case a.Status.PLAN_NOT_FOUND:b="Plan was not found!";break;case a.Status.PROMOCODE_NOT_FOUND:b=
"Promotion code not valid!";break;case a.Status.DEMOAPP_NOT_FOUND:b="This language has no demo content";break;case a.Status.MODULE_USE_FORBIDDEN:b="Required module is not attached to app";break;case a.Status.PUSH_ERROR_APIKEY:b="No API Key defined for Push service!";break;case a.Status.PUSH_ERROR_CERTIFICATE:b="No certificate defined for Push service!";break;case a.Status.SAME_NAME_USED_IN_SUPERCLASS:b="Same name is already used in a superclass.";break;case a.Status.PAYMENT_MAX_MODULE:b="Maximum number of used modules exceeded for this plan.";
break;case a.Status.PAYMENT_SYSTEM:b="Selected system use is not allowed for this plan.";break;case a.Status.PAYMENT_DOWNGRADE:b="Up/Downgrading plans is only allowed for super admins.";break;case a.Status.SAVE_REFERENECE_BEFORE_REFERENCING:b="Object you are trying to reference is not on the server. Please save it first.";break;case a.Status.PAYMENT_DB_SIZE:b="Used database size exceeds plan";break;case a.Status.ENDPOINT_PATH_NOT_ALLOWED:b="Endpoint not allowed for app; please add path to your app's config.";
break;case a.Status.PAYMENT_NO_CRON:b="Cronjobs are not allowed for this plan.";break;case a.Status.PAYMENT_MODULE_NOT_FREE:b="This module is not available for free plan.";break;case a.Status.NATIVEMODULE_DEACTIVATED:b="Native Module feature is not activated for this installation.";break;case a.Status.LICENSE_INVALID:b="Your license does not allow this action.";break;case a.Status.PAYMENT_NO_CUSTOMERROLES:b="Customer role usage is not available for free plan.";break;case a.Status.WHITELABEL:b="Only available at whitelabel installations.";
break;case a.Status.WHITELABEL_NOT:b="Not available at whitelabel installations.";break;case a.Status.MODULE_CONFIG_NO_DOT:b="No dot allowed in module config key.";break;case a.Status.PLAN_FALLBACK:b="Application cannot be activated without valid plan.";break;case a.Status.PLAN_INACTIVE:b="Plan is not selectable!";break;case a.Status.ID_EXISTS:b="ID exists!";break;case a.Status.NAME_RESERVED:b="Name is reserved!";break;case a.Status.CIRCULAR_DEPENDENCY:b="You can't set circular inheritance!";break;
case a.Status.NAME_EXISTS:b="Name is already used!";break;case a.Status.UNAUTHORIZED:b="Authorization failed!";break;case a.Status.WRONG_APIKEY:b="API Key was not correct!";break;case a.Status.EVALANCHE_UNAUTH:b="Authorization failed! Maybe username/password was not set for evelanche configuration?";break;case a.Status.PW_CHANGE_W_TOKEN:b="Not authorized to change a user's password when authenticating with a token.";break;case a.Status.TOKEN_AUTH_ERROR:b="The token could not be authenticated";break;
case a.Status.TOKEN_READ_ONLY:b="The token can only be used for read requests.";break;case a.Status.CRUD_ERROR:b="Internal error during CRUD operation";break;case a.Status.IMEXPORT_ERROR:b="Error during im/export!";break;case a.Status.COMPILE_ERROR:b="Classes could not be compiled!";break;case a.Status.REFERENCE_ERROR:b="Error in class reference!";break;case a.Status.PUSH_PAYLOAD_ERROR:b="Failed to create payload!";break;case a.Status.PUSH_SEND_ERROR:b="Failed to send message(s)!";break;case a.Status.PUSH_INIT_FAILED:b=
"Failed to initialize push service!";break;case a.Status.FACEBOOK_ERROR:b="An error occured while communicating with facebook!";break;case a.Status.FACEBOOK_OAUTH_ERROR:b="facebook throws oAuth error! Please show login dialog again";break;case a.Status.FACEBOOK_OAUTH_ERROR2:b="Received OAuth2 error from Facebook";break;case a.Status.MEMBER_NOT_FOUND:b="Can't find member with this id/username";break;case a.Status.WORDPRESS_FETCH_DATA_ERROR:b="Can't fetch data for wordpress blog";break;case a.Status.TUMBLR_OAUTH_ERROR:b=
"tumblr threw oAuth error! Please show login dialog again";break;case a.Status.TUMBLR_ERROR:b="Error communicating with tumblr!";break;case a.Status.EXECUTE_METHOD_ERROR_PRIMITIVE:b="Only primitive types are allowed";break;case a.Status.EXECUTE_METHOD_ERROR:b="Execute method failed";break;case a.Status.OAUTH_TOKEN_REQUEST_ERROR:b="An error occured during requesting an apiOmat OAuth2 token";break;case a.Status.FINDING_RESOURCE_ERROR:b="An error occured while trying to find the resource";break;case a.Status.NATIVEMODULE_DEPLOY:b=
"Executing onDeploy failed";break;case a.Status.TOKEN_SEARCH_ERROR:b="An error occured while searching for tokens";break;case a.Status.MODULE_CONFIG_MISSING:b="Your module seems not to be configured properly";break;case a.Status.HREF_NOT_FOUND:b="Class has no HREF; please save it first!";break;case a.Status.WRONG_URI_SYNTAX:b="URI syntax is wrong";break;case a.Status.WRONG_CLIENT_PROTOCOL:b="Client protocol is wrong";break;case a.Status.IO_EXCEPTION:b="IOException was thrown";break;case a.Status.UNSUPPORTED_ENCODING:b=
"Encoding is not supported";break;case a.Status.INSTANTIATE_EXCEPTION:b="Error on class instantiation";break;case a.Status.IN_PERSISTING_PROCESS:b="Object is in persisting process. Please try again later";break;case a.Status.VERIFY_SOCIALMEDIA:b="Can't verify against social media provider";break;case a.Status.TOO_MANY_LOCALIDS:b="Can't create more localIDs. Please try again later";break;case a.Status.MAX_CACHE_SIZE_REACHED:b="The maximum cache size is reached.";break;case a.Status.CANT_WRITE_IN_CACHE:b=
"Can't persist data to cache.";break;case a.Status.BAD_DATASTORE_CONFIG:b="For requesting a session token without a refresh token, the Datastore must be configured with a username and password";break;case a.Status.NO_TOKEN_RECEIVED:b="The response didn't contain a token";break;case a.Status.NO_NETWORK:b="No network connection available";break;case a.Status.ID_NOT_FOUND_OFFLINE:b="ID was not found in offline storage";break;case a.Status.ATTACHED_HREF_MISSING:b="HREF of attached image / file / reference is missing";
break;case a.Status.REQUEST_TIMEOUT:b="The request timed out during connecting or reading the response";break;case a.Status.ASYNC_WAIT_ERROR:b="An error occured during waiting for an async task to finish";break;case a.Status.IN_DELETING_PROCESS:b="Object is in deleting process. Please try again later";break;case a.Status.SSO_REDIRECT:b="The request was redirected to an SSO Identity Provider";break;case a.Status.MALICIOUS_MEMBER:b="Malicious use of member detected!";break;default:b="No reason found"}return b},
getStatusForCode:function(c){var b=void 0;switch(c){case 701:b=a.Status.SCRIPT_ERROR;break;case 702:b=a.Status.APPLICATION_NOT_ACTIVE;break;case 703:b=a.Status.BAD_IMAGE;break;case 704:b=a.Status.BAD_ID;break;case 705:b=a.Status.CONCURRENT_ACCESS;break;case 706:b=a.Status.APPLICATION_SANDBOX;break;case 707:b=a.Status.MODEL_NOT_DEPLOYED;break;case 709:b=a.Status.WRONG_REF_TYPE;break;case 710:b=a.Status.ATTRIBUTE_NOT_SET;break;case 711:b=a.Status.OPERATION_NOT_POSSIBLE;break;case 712:b=a.Status.APPLICATION_NAME_MISMATCH;
break;case 713:b=a.Status.WRONG_AUTH_HEADER;break;case 714:b=a.Status.MODEL_STILL_USED;break;case 715:b=a.Status.COLLECTION_NOT_ALLOWED;break;case 716:b=a.Status.FB_NO_VALID_MEMBER;break;case 717:b=a.Status.FB_NO_OAUTH_TOKEN;break;case 718:b=a.Status.FB_POST_ID_MISSING;break;case 719:b=a.Status.RESTORE_NO_DUMPS_FOUND;break;case 720:b=a.Status.TW_NO_VALID_MEMBER;break;case 721:b=a.Status.TW_NO_OAUTH_TOKEN;break;case 722:b=a.Status.IMEXPORT_WRONG_ENCODING;break;case 723:b=a.Status.IMEXPORT_WRONG_CONTENT;
break;case 724:b=a.Status.PUSH_PAYLOAD_EXCEEDED;break;case 725:b=a.Status.PUSH_ERROR;break;case 726:b=a.Status.BAD_EMAIL;break;case 727:b=a.Status.BAD_PROMOTIONCODE_DISCOUNT;break;case 728:b=a.Status.BAD_PROMOTIONCODE_CODE;break;case 729:b=a.Status.PLAN_PRICE;break;case 730:b=a.Status.PLAN_NO_SYSTEMS;break;case 731:b=a.Status.SCRIPT_TIME_ERROR;break;case 732:b=a.Status.INVALID_NAME;break;case 733:b=a.Status.ATTRIBUTE_IN_SUPERCLASS;break;case 734:b=a.Status.JSON_TYPE_ERROR;break;case 735:b=a.Status.TBLR_NO_VALID_MEMBER;
break;case 736:b=a.Status.TBLR_NO_OAUTH_TOKEN;break;case 737:b=a.Status.TBLR_POST_ID_MISSING;break;case 738:b=a.Status.LOCATION_INVALID;break;case 739:b=a.Status.SCRIPT_EXCEPTION;break;case 740:b=a.Status.BAD_CUSTOMERNAME;break;case 746:b=a.Status.BAD_IMAGE_ALPHA;break;case 747:b=a.Status.BAD_IMAGE_BGCOLOR;break;case 748:b=a.Status.BAD_IMAGE_FORMAT;break;case 708:b=a.Status.QUERY_ERROR;break;case 741:b=a.Status.BAD_TYPE_IN_QUERY;break;case 742:b=a.Status.UNKNOWN_CLASS_IN_QUERY;break;case 743:b=a.Status.WRONG_NUM_FORMAT_IN_QUERY;
break;case 744:b=a.Status.QUERY_PARSE_ERROR;break;case 745:b=a.Status.UNKNOWN_ATTRIBUTE_IN_QUERY;break;case 749:b=a.Status.FOREIGNID_NOT_SET;break;case 750:b=a.Status.CLASSES_MISSING;break;case 751:b=a.Status.INVALID_ATTRIBUTE_TYPE;break;case 752:b=a.Status.TOKEN_VALUE_EXISTS;break;case 753:b=a.Status.JSON_FORMAT_ERROR;break;case 754:b=a.Status.MODULE_DEPLOYMENT;break;case 755:b=a.Status.BAD_USERNAME;break;case 756:b=a.Status.CSV_ZIP_FORMAT;break;case 757:b=a.Status.VERIFICATION;break;case 758:b=
a.Status.MODULE_STILL_USED;break;case 759:b=a.Status.CLASS_NOT_IN_MODULE;break;case 760:b=a.Status.ORDER_TRANSACTION_TIMESTAMP_OUTDATED;break;case 761:b=a.Status.ORDER_TRANSACTION_ID_INVALID;break;case 762:b=a.Status.ORDER_TRANSACTION_SECRET_INVALID;break;case 763:b=a.Status.MANDATORY_FIELD;break;case 764:b=a.Status.INVALID_PASSWD_LENGTH;break;case 765:b=a.Status.BAD_PROMOTIONCODE_VALID;break;case 801:b=a.Status.APPLICATION_NOT_FOUND;break;case 802:b=a.Status.CUSTOMER_NOT_FOUND;break;case 803:b=a.Status.ID_NOT_FOUND;
break;case 804:b=a.Status.MODEL_NOT_FOUND;break;case 805:b=a.Status.MODULE_NOT_FOUND;break;case 806:b=a.Status.METAMODEL_NOT_FOUND;break;case 807:b=a.Status.PLAN_NOT_FOUND;break;case 808:b=a.Status.PROMOCODE_NOT_FOUND;break;case 809:b=a.Status.DEMOAPP_NOT_FOUND;break;case 820:b=a.Status.MODULE_USE_FORBIDDEN;break;case 821:b=a.Status.PUSH_ERROR_APIKEY;break;case 822:b=a.Status.PUSH_ERROR_CERTIFICATE;break;case 823:b=a.Status.SAME_NAME_USED_IN_SUPERCLASS;break;case 824:b=a.Status.PAYMENT_MAX_MODULE;
break;case 825:b=a.Status.PAYMENT_SYSTEM;break;case 826:b=a.Status.PAYMENT_DOWNGRADE;break;case 827:b=a.Status.SAVE_REFERENECE_BEFORE_REFERENCING;break;case 828:b=a.Status.PAYMENT_DB_SIZE;break;case 829:b=a.Status.ENDPOINT_PATH_NOT_ALLOWED;break;case 1820:b=a.Status.PAYMENT_NO_CRON;break;case 1821:b=a.Status.PAYMENT_MODULE_NOT_FREE;break;case 1822:b=a.Status.NATIVEMODULE_DEACTIVATED;break;case 1823:b=a.Status.LICENSE_INVALID;break;case 1824:b=a.Status.PAYMENT_NO_CUSTOMERROLES;break;case 1825:b=a.Status.WHITELABEL;
break;case 1826:b=a.Status.WHITELABEL_NOT;break;case 1827:b=a.Status.MODULE_CONFIG_NO_DOT;break;case 1828:b=a.Status.PLAN_FALLBACK;break;case 1829:b=a.Status.PLAN_INACTIVE;break;case 830:b=a.Status.ID_EXISTS;break;case 831:b=a.Status.NAME_RESERVED;break;case 832:b=a.Status.CIRCULAR_DEPENDENCY;break;case 833:b=a.Status.NAME_EXISTS;break;case 840:b=a.Status.UNAUTHORIZED;break;case 841:b=a.Status.WRONG_APIKEY;break;case 842:b=a.Status.EVALANCHE_UNAUTH;break;case 843:b=a.Status.PW_CHANGE_W_TOKEN;break;
case 844:b=a.Status.TOKEN_AUTH_ERROR;break;case 845:b=a.Status.TOKEN_READ_ONLY;break;case 901:b=a.Status.CRUD_ERROR;break;case 902:b=a.Status.IMEXPORT_ERROR;break;case 903:b=a.Status.COMPILE_ERROR;break;case 904:b=a.Status.REFERENCE_ERROR;break;case 905:b=a.Status.PUSH_PAYLOAD_ERROR;break;case 906:b=a.Status.PUSH_SEND_ERROR;break;case 907:b=a.Status.PUSH_INIT_FAILED;break;case 908:b=a.Status.FACEBOOK_ERROR;break;case 910:b=a.Status.FACEBOOK_OAUTH_ERROR;break;case 917:b=a.Status.FACEBOOK_OAUTH_ERROR2;
break;case 911:b=a.Status.MEMBER_NOT_FOUND;break;case 912:b=a.Status.WORDPRESS_FETCH_DATA_ERROR;break;case 913:b=a.Status.TUMBLR_OAUTH_ERROR;break;case 914:b=a.Status.TUMBLR_ERROR;break;case 915:b=a.Status.EXECUTE_METHOD_ERROR_PRIMITIVE;break;case 916:b=a.Status.EXECUTE_METHOD_ERROR;break;case 918:b=a.Status.OAUTH_TOKEN_REQUEST_ERROR;break;case 919:b=a.Status.FINDING_RESOURCE_ERROR;break;case 920:b=a.Status.NATIVEMODULE_DEPLOY;break;case 921:b=a.Status.TOKEN_SEARCH_ERROR;break;case 922:b=a.Status.MODULE_CONFIG_MISSING;
break;case 601:b=a.Status.HREF_NOT_FOUND;break;case 602:b=a.Status.WRONG_URI_SYNTAX;break;case 603:b=a.Status.WRONG_CLIENT_PROTOCOL;break;case 604:b=a.Status.IO_EXCEPTION;break;case 605:b=a.Status.UNSUPPORTED_ENCODING;break;case 606:b=a.Status.INSTANTIATE_EXCEPTION;break;case 607:b=a.Status.IN_PERSISTING_PROCESS;break;case 608:b=a.Status.VERIFY_SOCIALMEDIA;break;case 609:b=a.Status.TOO_MANY_LOCALIDS;break;case 610:b=a.Status.MAX_CACHE_SIZE_REACHED;break;case 611:b=a.Status.CANT_WRITE_IN_CACHE;break;
case 612:b=a.Status.BAD_DATASTORE_CONFIG;break;case 613:b=a.Status.NO_TOKEN_RECEIVED;break;case 614:b=a.Status.NO_NETWORK;break;case 615:b=a.Status.ID_NOT_FOUND_OFFLINE;break;case 616:b=a.Status.ATTACHED_HREF_MISSING;break;case 617:b=a.Status.REQUEST_TIMEOUT;break;case 618:b=a.Status.ASYNC_WAIT_ERROR;break;case 619:b=a.Status.IN_DELETING_PROCESS;break;case 620:b=a.Status.SSO_REDIRECT;break;case 950:b=a.Status.MALICIOUS_MEMBER}return b}}})("undefined"===typeof exports?Apiomat:exports);if("undefined"!==typeof goog)var XMLHttpRequest={};
if("undefined"===typeof Ti&&"undefined"!==typeof module&&module.exports){var Url=require("url"),spawn=require("child_process").spawn,fs=require("fs");exports.XMLHttpRequest=function(){var a=this,c=require("http"),b=require("https"),d,e,f,g,t,k,w,x=!1,r={"User-Agent":"node-XMLHttpRequest",Accept:"*/*"},p=r,u="accept-charset accept-encoding access-control-request-headers access-control-request-method connection content-length content-transfer-encoding cookie cookie2 date expect host keep-alive origin referer te trailer transfer-encoding upgrade via".split(" "),v=
["TRACE","TRACK","CONNECT"],n=!1,l=!1,m={};this.UNSENT=0;this.OPENED=1;this.HEADERS_RECEIVED=2;this.LOADING=3;this.DONE=4;this.readyState=this.UNSENT;this.onreadystatechange=null;this.responseXML=this.responseText="";this.statusText=this.status=null;this.open=function(a,b,c,d,e){this.abort();l=!1;if(!(a&&-1===v.indexOf(a)))throw"SecurityError: Request method not allowed";f=a;g=b.toString();t="boolean"!==typeof c?!0:c;k=d||null;w=e||null;s(this.OPENED)};this.setDisableHeaderCheck=function(a){x=a};
this.setRequestHeader=function(a,b){if(this.readyState!=this.OPENED)throw"INVALID_STATE_ERR: setRequestHeader can only be called when state is OPEN";if(x||a&&-1===u.indexOf(a.toLowerCase())){if(n)throw"INVALID_STATE_ERR: send flag is true";p[a]=b}else console.warn('Refused to set unsafe header "'+a+'"')};this.getResponseHeader=function(a){return"string"===typeof a&&this.readyState>this.OPENED&&e.headers[a.toLowerCase()]&&!l?e.headers[a.toLowerCase()]:null};this.getAllResponseHeaders=function(){if(this.readyState<
this.HEADERS_RECEIVED||l)return"";var a="",b;for(b in e.headers)"set-cookie"!==b&&"set-cookie2"!==b&&(a+=b+": "+e.headers[b]+"\r\n");return a.substr(0,a.length-2)};this.getRequestHeader=function(a){return"string"===typeof a&&p[a]?p[a]:""};this.send=function(m){if(this.readyState!=this.OPENED)throw"INVALID_STATE_ERR: connection must be opened before send() is called";if(n)throw"INVALID_STATE_ERR: send has already been called";var y=!1,h=!1,q=Url.parse(g),r;switch(q.protocol){case "https:":y=!0;case "http:":r=
q.hostname;break;case "file:":h=!0;break;case void 0:case "":r="localhost";break;default:throw"Protocol not supported.";}if(h){if("GET"!==f)throw"XMLHttpRequest: Only GET method is supported";if(t)fs.readFile(q.pathname,"utf8",function(b,c){b?a.handleError(b):(a.status=200,a.responseText=c,s(a.DONE))});else try{this.responseText=fs.readFileSync(q.pathname,"utf8"),this.status=200,s(a.DONE)}catch(u){this.handleError(u)}}else{var h=q.port||(y?443:80),v=q.pathname+(q.search?q.search:"");p.Host=r;y&&443===
h||80===h||(p.Host+=":"+q.port);k&&("undefined"==typeof w&&(w=""),q=new Buffer(k+":"+w),p.Authorization="Basic "+q.toString("base64"));"GET"===f||"HEAD"===f?m=null:m?(p["Content-Length"]=Buffer.isBuffer(m)?m.length:Buffer.byteLength(m),p["Content-Type"]||(p["Content-Type"]="text/plain;charset\x3dUTF-8")):"POST"===f&&(p["Content-Length"]=0);v={host:r,port:h,path:v,method:f,headers:p,agent:!1};l=!1;if(t){var x=y?b.request:c.request;n=!0;a.dispatchEvent("readystatechange");var A=function(b){e=b;302===
e.statusCode||303===e.statusCode||307===e.statusCode?(g=e.headers.location,b=Url.parse(g),r=b.hostname,d=x({hostname:b.hostname,port:b.port,path:b.path,method:303===e.statusCode?"GET":f,headers:p},A).on("error",F),d.end()):(e.setEncoding("utf8"),s(a.HEADERS_RECEIVED),a.status=e.statusCode,e.on("data",function(b){b&&(a.responseText+=b);n&&s(a.LOADING)}),e.on("end",function(){n&&(s(a.DONE),n=!1)}),e.on("error",function(b){a.handleError(b)}))},F=function(b){a.handleError(b)};d=x(v,A).on("error",F);m&&
d.write(m);d.end();a.dispatchEvent("loadstart")}else{q=".node-xmlhttprequest-content-"+process.pid;h=".node-xmlhttprequest-sync-"+process.pid;fs.writeFileSync(h,"","utf8");m="var http \x3d require('http'), https \x3d require('https'), fs \x3d require('fs');var doRequest \x3d http"+(y?"s":"")+".request;var options \x3d "+JSON.stringify(v)+";var responseText \x3d '';var req \x3d doRequest(options, function(response) {response.setEncoding('utf8');response.on('data', function(chunk) {  responseText +\x3d chunk;});response.on('end', function() {fs.writeFileSync('"+
q+"', 'NODE-XMLHTTPREQUEST-STATUS:' + response.statusCode + ',' + responseText, 'utf8');fs.unlinkSync('"+h+"');});response.on('error', function(error) {fs.writeFileSync('"+q+"', 'NODE-XMLHTTPREQUEST-ERROR:' + JSON.stringify(error), 'utf8');fs.unlinkSync('"+h+"');});}).on('error', function(error) {fs.writeFileSync('"+q+"', 'NODE-XMLHTTPREQUEST-ERROR:' + JSON.stringify(error), 'utf8');fs.unlinkSync('"+h+"');});"+(m?"req.write('"+m.replace(/'/g,"\\'")+"');":"")+"req.end();";for(m=spawn(process.argv[0],
["-e",m]);fs.existsSync(h););a.responseText=fs.readFileSync(q,"utf8");m.stdin.end();fs.unlinkSync(q);a.responseText.match(/^NODE-XMLHTTPREQUEST-ERROR:/)?(m=a.responseText.replace(/^NODE-XMLHTTPREQUEST-ERROR:/,""),a.handleError(m)):(a.status=parseInt(a.responseText.replace(/^NODE-XMLHTTPREQUEST-STATUS:([0-9]*),.*/,"$1"),10),a.responseText=a.responseText.replace(/^NODE-XMLHTTPREQUEST-STATUS:[0-9]*,(.*)/,"$1"),s(a.DONE))}}};this.handleError=function(a){this.status=503;this.statusText=a;this.responseText=
a.stack;l=!0;s(this.DONE)};this.abort=function(){d&&(d.abort(),d=null);p=r;this.responseXML=this.responseText="";l=!0;if(this.readyState!==this.UNSENT&&(this.readyState!==this.OPENED||n)&&this.readyState!==this.DONE)n=!1,s(this.DONE);this.readyState=this.UNSENT};this.addEventListener=function(a,b){a in m||(m[a]=[]);m[a].push(b)};this.removeEventListener=function(a,b){a in m&&(m[a]=m[a].filter(function(a){return a!==b}))};this.dispatchEvent=function(b){if("function"===typeof a["on"+b])a["on"+b]();
if(b in m)for(var c=0,d=m[b].length;c<d;c++)m[b][c].call(a)};var s=function(b){a.readyState!==b&&(a.readyState=b,(t||a.readyState<a.OPENED||a.readyState===a.DONE)&&a.dispatchEvent("readystatechange"),a.readyState===a.DONE&&!l&&(a.dispatchEvent("load"),a.dispatchEvent("loadend")))}}};"undefined"!==typeof goog&&(Apiomat.AOMHelper={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMHelper=function(){return{isTitaniumApp:function(){return"object"===typeof Ti},sendEvent:function(c,b){var d=void 0;a.AOMHelper.isTitaniumApp()?Ti.App.fireEvent(c,b||{}):("undefined"!==typeof CustomEvent?d=new CustomEvent(c,b||{}):(d=document.createEvent("Event"),d.initEvent(c,!0,!0),d.customData=b||{}),window.dispatchEvent(d))},addEventListener:function(c,b){a.AOMHelper.isTitaniumApp()?Ti.App.addEventListener(c,b):window.addEventListener(c,b)}}}()})("undefined"===typeof exports?
Apiomat:exports);Array.prototype.filter||(Array.prototype.filter=function(a,c){if(!this)throw new TypeError;var b=Object(this);if("function"!==typeof a)throw new TypeError;var d=[],e;for(e in b)b.hasOwnProperty(e)&&a.call(c,b[e],e,b)&&d.push(b[e]);return d});String.prototype.endsWith||(String.prototype.endsWith=function(a){return-1!==this.indexOf(a,this.length-a.length)});
Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,c=!{toString:null}.propertyIsEnumerable("toString"),b="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),d=b.length;return function(e){if("object"!==typeof e&&("function"!==typeof e||null===e))throw new TypeError("Object.keys called on non-object");var f=[],g;for(g in e)a.call(e,g)&&f.push(g);if(c)for(g=0;g<d;g++)a.call(e,b[g])&&f.push(b[g]);return f}}());if("undefined"!==typeof goog)var base64={};
(function(a){if(!a.Base64){var c=function(a){for(var b={},c=0,d=a.length;c<d;c++)b[a.charAt(c)]=c;return b}("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"),b=String.fromCharCode,d=function(a){if(2>a.length){var c=a.charCodeAt(0);return 128>c?a:2048>c?b(192|c>>>6)+b(128|c&63):b(224|c>>>12&15)+b(128|c>>>6&63)+b(128|c&63)}c=65536+1024*(a.charCodeAt(0)-55296)+(a.charCodeAt(1)-56320);return b(240|c>>>18&7)+b(128|c>>>12&63)+b(128|c>>>6&63)+b(128|c&63)},e=/[\uD800-\uDBFF][\uDC00-\uDFFFF]|[^\x00-\x7F]/g,
f=function(a){return a.replace(e,d)},g=function(a){var b=[0,2,1][a.length%3];a=a.charCodeAt(0)<<16|(1<a.length?a.charCodeAt(1):0)<<8|(2<a.length?a.charCodeAt(2):0);return["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>18),"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>12&63),2<=b?"\x3d":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>6&63),1<=b?"\x3d":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a&
63)].join("")},t=a.btoa||function(a){return a.replace(/[\s\S]{1,3}/g,g)},k=function(a,b){return!b?t(f(a)):t(f(a)).replace(/[+\/]/g,function(a){return"+"==a?"-":"_"}).replace(/=/g,"")},w=/[\u00c0-\u00df][\u0080-\u00bf]|[\u00e0-\u00ef][\u0080-\u00bf]{2}|[\u00f0-\u00f7][\u0080-\u00bf]{3}/g,x=function(a){switch(a.length){case 4:return a=((7&a.charCodeAt(0))<<18|(63&a.charCodeAt(1))<<12|(63&a.charCodeAt(2))<<6|63&a.charCodeAt(3))-65536,b((a>>>10)+55296)+b((a&1023)+56320);case 3:return b((15&a.charCodeAt(0))<<
12|(63&a.charCodeAt(1))<<6|63&a.charCodeAt(2));default:return b((31&a.charCodeAt(0))<<6|63&a.charCodeAt(1))}},r=function(a){return a.replace(w,x)},p=function(a){var d=a.length,e=d%4;a=(0<d?c[a.charAt(0)]<<18:0)|(1<d?c[a.charAt(1)]<<12:0)|(2<d?c[a.charAt(2)]<<6:0)|(3<d?c[a.charAt(3)]:0);a=[b(a>>>16),b(a>>>8&255),b(a&255)];a.length-=[0,0,2,1][e];return a.join("")},u=a.atob||function(a){return a.replace(/[\s\S]{1,4}/g,p)},v=function(a){return r(u(a))},n=function(a){return v(a.replace(/[-_]/g,function(a){return"-"==
a?"+":"/"}).replace(/[^A-Za-z0-9\+\/]/g,""))};a.Base64={VERSION:"2.1.2",atob:u,btoa:t,fromBase64:n,toBase64:k,utob:f,encode:k,encodeURI:function(a){return k(a,!0)},btou:r,decode:n};if("function"===typeof Object.defineProperty){var l=function(a){return{value:a,enumerable:!1,writable:!0,configurable:!0}};a.Base64.extendString=function(){Object.defineProperty(String.prototype,"fromBase64",l(function(){return n(this)}));Object.defineProperty(String.prototype,"toBase64",l(function(a){return k(this,a)}));
Object.defineProperty(String.prototype,"toBase64URI",l(function(){return k(this,!0)}))}}}})(this);"undefined"!==typeof goog&&(Apiomat.AOMFileHandler={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMFileHandler=function(){var a={},b=void 0;if("undefined"!==typeof window&&window.File&&window.FileReader&&window.FileList&&window.Blob){var d=function(a){console.log(a.target.error.code)},e=function(a){b=a},f=window.PERSISTENT;!f&&"undefined"!==typeof LocalFileSystem&&(f=LocalFileSystem.PERSISTENT);f&&"undefined"!==typeof window&&window.requestFileSystem&&window.requestFileSystem(f,0,e,d)}this.getAppDirectory=function(a,c){"undefined"!==typeof b?b.root.getDirectory("apiomatpersists",
{create:!0},function(b){a&&a(b)},function(a){console.error("Can't get directory handle!!");c&&c(a)}):a&&a(void 0)};this.getFileHandler=function(a,b,c,d){this.getAppDirectory(function(d){"undefined"!==typeof d?d.getFile(a,{},function(a){b&&b(a)},c):c()},c)};this.getSizeOfAppDir=function(a,c){if("undefined"!==typeof b){var d=this,e=function(a,b,f,g,n,l){f>=a.length?n(g):d.getFileHandler(b,function(b){b.file(function(b){g+=b.size;b=void 0;"undefined"!==typeof a[++f]&&(b=a[f].name);e(a,b,f,g,n,l)},l)},
function(b){b.code!==FileError.NOT_FOUND_ERR&&c?l(b):("undefined"!==typeof a[++f]&&(nextName=a[f].name),e(a,_nextName,f,g,n,l))})},f=function(b){void 0!==typeof b&&0<b.length?e(b,b[0].name,0,0,function(b){a&&a(b)},c):a&&a(0)};this.getAppDirectory(function(a){a.createReader().readEntries(f,c)},c)}else a&&a(0)};this.createFileName=function(a){return a+"_"+(new Date).getTime()};this.removeFile=function(d,e,f){"undefined"!==typeof b?this.getFileHandler(d,function(a){a.remove(function(){e&&e()},f)},function(a){a.code!==
FileError.NOT_FOUND_ERR&&f?f(a):e&&e()}):(delete a[d],e&&e())};this.readFile=function(d,e,f){"undefined"!==typeof b?this.getFileHandler(d,function(a){a.file(function(a){var b=new FileReader;b.onloadend=function(a){e&&e(a.target.result)};b.readAsText(a)})},function(a){a.code!==FileError.NOT_FOUND_ERR&&f?f(a):e&&e(void 0)}):e&&e(a[d])};this.writeFile=function(d,e,f,w){"undefined"!==typeof b?this.getFileHandler(d,function(a){a.createWriter(function(a){a.onwriteend=function(a){f&&f()};a.write(e)},w)},
w,{create:!0,exclusive:!1}):(a[d]=e,f&&f())}};a.AOMFileHandler.HREFMAP_FILENAME="hrefMap";a.AOMFileHandler.USEDLOCALIDS_FILENAME="usedLocalIDs";a.AOMFileHandler.TASKLIST_FILENAME="taskList";a.AOMFileHandler.prototype={}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMNetworkHandler={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMNetworkHandler=function(){return{AOMNETWORKEVENT:"AomNetworkEvent",isChecking:!1,checkForConnection:function(){a.AOMNetworkHandler.isChecking=!0;!1===a.AOMNetworkHandler.isConnected()?setTimeout(a.AOMNetworkHandler.checkForConnection,150):(console.log("Connection is back..."),a.AOMNetworkHandler.isChecking=!1,a.AOMHelper.sendEvent(a.AOMNetworkHandler.AOMNETWORKEVENT,{isConnected:!0}))},isConnected:function(){var c=!0,c=a.AOMHelper.isTitaniumApp()?Titanium.Network.online:navigator.online;
!0===a.forceOffline&&(c=!a.forceOffline);!1===c&&!1===a.AOMNetworkHandler.isChecking&&a.AOMNetworkHandler.checkForConnection();return c}}}()})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMFileHandlerTi={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMFileHandlerTi=function(){var a=function(){var a=Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory,"apiomatpersists");!1===a.exists()&&a.createDirectory();return a};this.getAppDirectory=function(b,d){var e=a();"undefined"===typeof e&&d?d():b&&b(e.nativePath)};this.getSizeOfAppDir=function(b,d){var e=a();"undefined"===typeof e&&d?d():b&&b(e.size)}};a.AOMHelper.isTitaniumApp()&&(a.AOMFileHandlerTi.prototype=new a.AOMFileHandler,a.AOMFileHandlerTi.prototype.constructor=a.AOMFileHandlerTi,
a.AOMFileHandlerTi.prototype.removeFile=function(a,b,d){var e=!1;this.getAppDirectory(function(f){f=Ti.Filesystem.getFile(f,a);f.exists()&&f.writeable&&(e=f.deleteFile());e?b&&b():d&&d()},d)},a.AOMFileHandlerTi.prototype.readFile=function(a,b,d){this.getAppDirectory(function(d){var f=void 0;d=Ti.Filesystem.getFile(d,a);d.exists()&&(f=d.read());f&&"undefined"!==typeof f?b&&b(f.text):b&&b(void 0)},d)},a.AOMFileHandlerTi.prototype.writeFile=function(a,b,d,e){this.getAppDirectory(function(f){Ti.Filesystem.getFile(f,
a).write(b)?d&&d():e&&e()},e)})})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.ApiomatRequestError={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.ApiomatRequestError=function(c,b,d){this.message=d||a.Status.getReasonPhrase(c);this.name="ApiomatRequestError";this.expectedCodes=b;this.statusCode=c;this.getStatusObj=function(){return a.Status.getStatusForCode(this.statusCode)}};a.ApiomatRequestError.prototype=Error();a.ApiomatRequestError.prototype.constructor=a.ApiomatRequestError})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Datastore={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMOfflineStrategy={NO_OFFLINE_HANDLING:0,USE_OFFLINE_CACHE:1};a.AOMAuthType={GUEST:0,USERNAME_PASSWORD:1,OAUTH2_TOKEN:2};a.Datastore=function(){function c(b,c,d,e,f,g,h){n=b;l=c;m=d;s=e;v=f;u=g;B=h;q="undefined"!==typeof B?a.AOMAuthType.OAUTH2_TOKEN:"undefined"!==typeof v&&"undefined"!==typeof u?a.AOMAuthType.USERNAME_PASSWORD:a.AOMAuthType.GUEST;C=!0}function b(){return{getUsername:function(){return v},getPassword:function(){return u},getAuthType:function(){return q},setUseAsnycRequests:function(a){D=
a},loadFromServer:function(b,c,d,e,l,g){f("GET",b,[200,304],!d?c:{onOk:function(b){d.fromJson(b);a.Datastore.positiveCallback(c)},onError:function(b){a.Datastore.negativeCallback(c,b)}},g,{data:l,withReferencedHrefs:e})},getOrCreateUser:function(b,c){var d=a.User.AOMBASEURL.substring(a.User.AOMBASEURL.lastIndexOf("/")+1),d=n.substring(0,n.indexOf("yambas/rest")+11)+"/modules/facebook/spec/"+d+"/aomuser?facebookToken\x3d"+b;f("GET",d,[200],c,void 0,void 0)},setCheckObjectState:function(a){C=a},getCheckObjectState:function(){return C},
loadResource:function(a,b){f("GET",a,[200,206],b,void 0,{isByteData:!0})},loadListFromServerWithClass:function(a,b,c,d){f("GET",w(a),[200,304],c,a,{data:b,withReferencedHrefs:d})},postOnServer:function(a,b,c){c||(c=k(a));f("POST",c,[201],b,void 0,{data:a.toJson()})},updateOnServer:function(a,b){var c=a.getHref(),d=a.toJson();f("PUT",c,[200],b,void 0,{data:d})},updateOnServerWithJSON:function(a,b,c){f("PUT",a,[200],c,void 0,{data:b})},deleteOnServer:function(a,b){d(a,void 0,b)},deleteModelOnServer:function(a,
b){d(void 0,a,b)},postStaticDataOnServer:function(a,b,c){b=x(b);this.postStaticDataOnServerWithHref(a,b,c)},postStaticDataOnServerWithHref:function(a,b,c){f("POST",b,[201],c,void 0,{isByteData:!0,data:a})},shouldSendOffline:function(b){return this.getOfflineStrategy()!=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING&&void 0!=this.getOfflineHandler()&&!1===this.getOfflineHandler().isConnected()},getOfflineHandler:function(){return h},getOfflineStrategy:function(){return y},sendOffline:function(b,c,d,e,f){!c&&
d instanceof a.AbstractClientDataModel?c=k(d):c||(c=x(e));this.getOfflineHandler().addTask(b,c,d,e,function(c){"POST"===b&&c?a.Datastore.positiveCallback(f,c):a.Datastore.positiveCallback(f)},function(c){"undefined"!==typeof f?("POST"===b&&(c=new a.ApiomatRequestError(a.Status.CRUD_ERROR,201,"Can't save offline")),a.Datastore.negativeCallback(f,c)):"undefined"!==typeof console&&console.error&&console.error("Can't send request to offline queue: "+c)})},requestSessionToken:function(b){if(q!==a.AOMAuthType.USERNAME_PASSWORD){var c=
new a.ApiomatRequestError(a.Status.BAD_DATASTORE_CONFIG);"undefined"!==typeof b?a.Datastore.negativeCallback(b,c):"undefined"!==typeof console&&console.error&&console.error("Error occured: "+c)}else c=n.substring(n.lastIndexOf("/")+1),e({grant_type:"aom_user",client_id:c,client_secret:l,scope:"read write",username:v,password:u,app:c,system:m},b)},requestSessionTokenWithRefreshToken:function(a,b){var c={grant_type:"refresh_token",client_id:n.substring(n.lastIndexOf("/")+1),client_secret:l,refresh_token:a};
e(c,b)},loadCountFromServer:function(b,c,d,e){var l=void 0,l="string"===typeof b&&"undefined"!==typeof c?b+"/"+c:w(b);f("GET",l+"/count",[200],{onOk:function(b){a.Datastore.positiveCallback(e,Number(b))},onError:function(b){typeof e&&a.Datastore.negativeCallback(e,b)}},void 0,{data:d,returnpost:!0})}}}function d(b,c,d){b?f("DELETE",b,[204],d):c&&c.getHref()?f("DELETE",c.getHref(),[204],d):(b=new a.ApiomatRequestError(a.Status.HREF_NOT_FOUND),d?a.Datastore.negativeCallback(d,b):console&&console.error&&
console.error("Error occured: "+b))}function e(b,c){var d=n.substring(0,n.indexOf("yambas")+6)+"/oauth/token",e="";for(prop in b)""!==e&&(e+="\x26"),e+=prop+"\x3d"+b[prop];f("POST",d,[200],{onOk:function(b){var d={};b=JSON.parse(b)||{};d.sessionToken=b.access_token;d.refreshToken=b.refresh_token;var e=b.expires_in||0;d.expirationDate=(new Date).getTime()+e;d.module=b.aom_module;d.model=b.aom_model;a.Datastore.positiveCallback(c,d)},onError:function(b){b=new a.ApiomatRequestError(b.statusCode,200,
"Requesting the session token failed");"undefined"!==typeof c?a.Datastore.negativeCallback(c,b):console&&console.error&&console.error("Error occured: "+b)}},void 0,{data:e,returnpost:!0,headerDetails:{authHeader:!1,contentType:"application/x-www-form-urlencoded"}})}function f(b,c,d,e,f,l){l=l||{};var m=l.data||void 0,s=l.withReferencedHrefs||void 0,h=l.isByteData||!1,q=l.returnpost||!1,y=l.headerDetails||{},k;z?(Ti.API.log("Use HTTP client of titanium"),k=Ti.Network.createHTTPClient({onload:function(a){g(this,
d,e,b,f,q,c)},onerror:function(b){var c=b.error||"";if(-1<c.indexOf("connection failure"))b=new a.ApiomatRequestError(a.Status.NO_NETWORK,d,c);else{if(-1<d.indexOf(this.status))throw b;b=new a.ApiomatRequestError(this.status,d,this.responseText)}"undefined"!==typeof e?a.Datastore.negativeCallback(e,b):Ti.API.error("Received HTTP error: "+b)}})):k="object"===typeof window&&window.XMLHttpRequest?new XMLHttpRequest:A?new exports.XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");"GET"===b&&m&&(c+=
"?q\x3d"+encodeURIComponent(m));var p=!1,p=r();"GET"===b&&(!1!=p&&10>=p)&&(c=m?c+"\x26":c+"?",c+="dIE\x3d"+(new Date).getTime());"GET"===b&&("undefined"!=typeof s&&!0==s)&&(c=m||!1!=p&&10>=p?c+"\x26":c+"?",c+="withReferencedHrefs\x3d"+s);c="http"===c.substring(0,4)?c:"/apps"===c.substring(0,5)?n.substring(0,n.indexOf("/apps"))+c:n+"/"+c;k.open(b,c,D);t(c,b,k,h,y);h&&"GET"===b&&k.overrideMimeType("text/plain; charset\x3dx-user-defined");!1==z&&(k.onreadystatechange=function(){4==k.readyState&&g(k,
d,e,b,f,q,c)});("POST"===b||"PUT"===b)&&"undefined"!==typeof m?l&&l.isByteData?(l=m,!1===z&&(l=(new Uint8Array(m)).buffer),k.send(l)):k.send(m):k.send()}function g(b,c,d,e,f,l,g){var m=!1;try{if(-1<c.indexOf(b.status)){if(d&&d.hasOwnProperty("onOk")){E&&"GET"===e&&b.getResponseHeader("Last-Modified");var s=b.responseText;if("GET"===e&&"undefined"!==typeof f){var h=JSON.parse(s);if(h instanceof Array){s=[];for(g=0;g<h.length;g++){var q=new f;q.fromJson(h[g]);s.push(q)}}else s=new f,s.fromJson(h)}f=
void 0;"POST"===e&&!1===l&&(f=b.getResponseHeader("Location"));a.Datastore.positiveCallback(d,"GET"===e||l?s:f||void 0)}}else m=!0}catch(k){z&&Ti.API.log("Error occured: "+k);if(b&&-1<c.indexOf(b.status))throw k;m=!0}finally{m&&(console.log("Status: "+b.status),b=new a.ApiomatRequestError(b.status,c,b.responseText),"undefined"!==typeof d?a.Datastore.negativeCallback(d,b):"undefined"!==typeof console&&console.error&&console.error("Error occured: "+b))}}function t(b,c,d,e,f){d.setRequestHeader("X-apiomat-system",
m);d.setRequestHeader("X-apiomat-apikey",l);f.contentType?d.setRequestHeader("Content-Type",f.contentType):"undefined"!==typeof e&&e?d.setRequestHeader("Content-Type","application/octet-stream"):(d.setRequestHeader("Content-Type","application/json"),d.setRequestHeader("Accept","application/json"));d.setRequestHeader("X-apiomat-fullupdate","true");if(!(f.hasOwnProperty("authHeader")&&!1==f.authHeader))if(q===a.AOMAuthType.USERNAME_PASSWORD){b=v+":"+u;if(A)try{b=(new (require("buffer").Buffer)(b)).toString("base64")}catch(g){b=
Base64.Base64.encode(b)}else try{b=Base64.encode(b)}catch(h){b=Base64.Base64.encode(b)}d.setRequestHeader("Authorization","Basic "+b)}else q===a.AOMAuthType.OAUTH2_TOKEN&&d.setRequestHeader("Authorization","Bearer "+B);d.setRequestHeader("X-apiomat-sdkVersion",s);(E||z)&&"GET"===c&&d.setRequestHeader("If-Modified-Since","01.01.1970 00:00:00:00 CEST")}function k(a){var b=n,b=b+"/models/"+a.getModuleName(),b=b+"/";return b+=a.getSimpleName()}function w(a){var b=n,b=b+"/models/"+a.prototype.getModuleName.call(),
b=b+"/";return b+=a.prototype.getSimpleName.call()}function x(a){var b=n,b=b+"/data/"+(a?"images":"files");return b+="/"}function r(){var a=window.navigator.userAgent,b=a.indexOf("MSIE ");if(0<b)return parseInt(a.substring(b+5,a.indexOf(".",b)),10);if(0<a.indexOf("Trident/"))return b=a.indexOf("rv:"),parseInt(a.substring(b+3,a.indexOf(".",b)),10);b=a.indexOf("Edge/");return 0<b?parseInt(a.substring(b+5,a.indexOf(".",b)),10):!1}var p,u,v,n,l,m,s,D=!0,y=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING,h=void 0,
q=a.AOMAuthType.GUEST,B,C=void 0,E="object"===typeof navigator&&0>=navigator.userAgent.indexOf("Chrom")&&-1<navigator.userAgent.indexOf("Safari")||!1,z="object"===typeof Ti||"object"===typeof Titanium,A=!1===z&&"undefined"!==typeof module&&module.exports;return{getInstance:function(){p||(p=b());return p},isInstantiated:function(){return"undefined"!==typeof p&&p},positiveCallback:function(a,b){if("undefined"!==typeof a&&a!={})for(var c in a){var d="function"==typeof a[c]&&"onok"==c.toString().toLowerCase()?
c.toString():void 0;if("undefined"!=typeof d){if(b&&"undefined"!=typeof b)a[d](b);else a[d]();break}}},negativeCallback:function(a,b){if("undefined"!==typeof a&&a!={})for(var c in a){var d="function"==typeof a[c]&&"onerror"==c.toString().toLowerCase()?c.toString():void 0;if("undefined"!=typeof d){if(b&&"undefined"!=typeof b)a[d](b);else a[d]();break}}},configure:function(a){this.configureWithCredentials(a)},configureWithCredentials:function(b){c(a.User.AOMBASEURL,a.User.AOMAPIKEY,a.User.AOMSYS,a.User.AOMSDKVERSION,
b.getUserName(),b.getPassword())},configureAsGuest:function(a,b,d,e){c(a,b,d,e)},configureWithUserSessionToken:function(a){this.configureWithSessionToken(a.getSessionToken())},configureWithSessionToken:function(b){c(a.User.AOMBASEURL,a.User.AOMAPIKEY,a.User.AOMSYS,a.User.AOMSDKVERSION,void 0,void 0,b)},configurePlain:function(a,b,c,d){this.configureAsGuest(a,b,c,d)},setOfflineStrategy:function(b,c){y=b;!h&&y!=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING&&(h=new a.AOMOfflineHandler);!h&&y!=a.AOMOfflineStrategy.NO_OFFLINE_HANDLING&&
(h=new a.AOMOfflineHandler);"undefined"!==typeof h&&("undefined"!==typeof c?h.init(c.onOk||void 0,c.onError||void 0):h.init(void 0,void 0))}}}()})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AbstractClientDataModel={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.ObjectState={DELETING:"DELETING",DELETED:"DELETED",PERSISTING:"PERSISTING",PERSISTED:"PERSISTED",LOCAL_PERSISTED:"LOCAL_PERSISTED",LOCAL_DELETED:"LOCAL_DELETED"};a.AbstractClientDataModel=function(){this.data={};this.toJson=function(){this.getHref()&&(this.data.id=this.getID());this.data["@type"]=this.getType();var a=JSON.stringify(this.data);delete this.data.id;return a};this.fromJson=function(c){if("object"===typeof c)for(var b in c)this.data[b]=c[b];else this.data=JSON.parse(c);
this.setCurrentState(a.ObjectState.PERSISTED);return this};this.getCurrentState=function(){return this.currentState};this.setCurrentState=function(a){this.currentState=a}};a.AbstractClientDataModel.prototype={getModuleName:function(){throw new a.ApiomatRequestError(void 0,void 0,"Must be implemented by child");},getSimpleName:function(){throw new a.ApiomatRequestError(void 0,void 0,"Must be implemented by child");},getType:function(){return this.getModuleName()+"$"+this.getSimpleName()},getHref:function(){return this.data.href},
getRefModelHrefs:function(){return this.data.referencedHrefs},getRefModelHrefsForName:function(a){var b=this.getRefModelHrefs();return b.hasOwnProperty(a)||a in b?b[a]:null},getAllowedRolesGrant:function(){return this.data.allowedRolesGrant},setAllowedRolesGrant:function(a){this.data.allowedRolesGrant=a},getAllowedRolesWrite:function(){return this.data.allowedRolesWrite},setAllowedRolesWrite:function(a){this.data.allowedRolesWrite=a},getAllowedRolesRead:function(){return this.data.allowedRolesRead},
setAllowedRolesRead:function(a){this.data.allowedRolesRead=a},getRstrictResourceAccess:function(){return this.data.restrictResourceAccess},setRestrictResourceAccess:function(a){this.data.restrictResourceAccess=a},getForeignId:function(){return this.data.foreignId},setForeignId:function(a){this.data.foreignId=a},getCreatedAt:function(){return new Date(this.data.createdAt)},getLastModifiedAt:function(){return new Date(this.data.lastModifiedAt)},getAppName:function(){return this.data.applicationName},
load:function(a){this.loadWithHref(void 0,a)},loadAndRefHref:function(a){this.loadWithHrefAndRefHref(void 0,a)},loadWithHref:function(c,b){if(this.isIllegalState()){var d="Object is in persisting or deleting process. Please try again later";this.getCurrentState()==a.ObjectState.PERSISTING?d=new a.ApiomatRequestError(a.Status.IN_PERSISTING_PROCESS,201,"Object is in persisting process. Please try again later"):this.getCurrentState()==a.ObjectState.DELETING&&(d=new a.ApiomatRequestError(a.Status.IN_DELETING_PROCESS,
201,"Object is in deleting process. Please try again later"));a.Datastore.negativeCallback(b,d)}else a.Datastore.getInstance().loadFromServer(c||this.getHref(),b,this,!1)},loadWithHrefAndRefHref:function(c,b){if(this.isIllegalState()){var d="Object is in persisting or deleting process. Please try again later";this.getCurrentState()==a.ObjectState.PERSISTING?d=new a.ApiomatRequestError(a.Status.IN_PERSISTING_PROCESS,201,"Object is in persisting process. Please try again later"):this.getCurrentState()==
a.ObjectState.DELETING&&(d=new a.ApiomatRequestError(a.Status.IN_DELETING_PROCESS,201,"Object is in deleting process. Please try again later"));a.Datastore.negativeCallback(b,d)}else a.Datastore.getInstance().loadFromServer(c||this.getHref(),b,this,!0)},save:function(c,b){if(this.isIllegalState()){var d="Object is in persisting or deleting process. Please try again later";this.getCurrentState()==a.ObjectState.PERSISTING?d=new a.ApiomatRequestError(a.Status.IN_PERSISTING_PROCESS,201,"Object is in persisting process. Please try again later"):
this.getCurrentState()==a.ObjectState.DELETING&&(d=new a.ApiomatRequestError(a.Status.IN_DELETING_PROCESS,201,"Object is in deleting process. Please try again later"));a.Datastore.negativeCallback(c,d)}else this.setCurrentState(a.ObjectState.PERSISTING),b="undefined"!==typeof b&&b.constructor===Boolean?b:!0,d={onOk:function(d){!this.parent.getHref()&&d&&(this.parent.data.href=d);this.parent.setOffline(this.wasLocalSave||!1);!this.wasLocalSave&&b?(this.parent.setCurrentState(a.ObjectState.PERSISTED),
this.parent.load({onOk:function(){a.Datastore.positiveCallback(c)},onError:function(b){a.Datastore.negativeCallback(c,b)}})):(this.parent.setCurrentState(a.ObjectState.LOCAL_PERSISTED),a.Datastore.positiveCallback(c))},onError:function(b){a.Datastore.negativeCallback(c,b)},parent:this},this.getHref()?a.Datastore.getInstance().shouldSendOffline("PUT")?(d.wasLocalSave=!0,a.Datastore.getInstance().sendOffline("PUT",this.getHref(),this,void 0,d)):a.Datastore.getInstance().updateOnServer(this,d):a.Datastore.getInstance().shouldSendOffline("POST")?
(d.wasLocalSave=!0,a.Datastore.getInstance().sendOffline("POST",void 0,this,void 0,d)):a.Datastore.getInstance().postOnServer(this,d)},deleteModel:function(c){if(this.isIllegalState()){var b="Object is in persisting or deleting process. Please try again later";this.getCurrentState()==a.ObjectState.PERSISTING?b=new a.ApiomatRequestError(a.Status.IN_PERSISTING_PROCESS,201,"Object is in persisting process. Please try again later"):this.getCurrentState()==a.ObjectState.DELETING&&(b=new a.ApiomatRequestError(a.Status.IN_DELETING_PROCESS,
201,"Object is in deleting process. Please try again later"));a.Datastore.negativeCallback(c,b)}else this.setCurrentState(a.ObjectState.DELETING),b={onOk:function(b){this.parent.setCurrentState(this.finishedState);"undefined"!=typeof b?a.Datastore.positiveCallback(c,b):a.Datastore.positiveCallback(c)},onError:function(b){a.Datastore.negativeCallback(c,b)},parent:this},a.Datastore.getInstance().shouldSendOffline("DELETE")?(b.finishedState=a.ObjectState.LOCAL_DELETED,a.Datastore.getInstance().sendOffline("DELETE",
this.getHref(),this,void 0,b)):(b.finishedState=a.ObjectState.DELETED,a.Datastore.getInstance().deleteModelOnServer(this,b))},isOffline:function(){return this.data.isOffline||!1},setOffline:function(a){this.data.isOffline=a},getID:function(){return this.getHref().substring(this.getHref().lastIndexOf("/")+1)},getAllObjectStates:function(){return this.ObjectState},isIllegalState:function(){var c=!1;a.Datastore.getInstance().getCheckObjectState()&&(c=this.getCurrentState()==a.ObjectState.PERSISTING||
this.getCurrentState()==a.ObjectState.DELETING);return c}}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.ChatMessageModel={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.ChatMessageModel=function(){this.init()};a.ChatMessageModel.getChatMessageModels=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.ChatMessageModel,c,b,!1)};a.ChatMessageModel.getChatMessageModelsAndRefHref=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.ChatMessageModel,c,b,d)};a.ChatMessageModel.getChatMessageModelsCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.ChatMessageModel,void 0,c,b)};a.ChatMessageModel.prototype=
new a.AbstractClientDataModel;a.ChatMessageModel.prototype.constructor=a.ChatMessageModel;a.ChatMessageModel.prototype.init=function(){this.data={}};a.ChatMessageModel.prototype.getSimpleName=function(){return"ChatMessageModel"};a.ChatMessageModel.prototype.getModuleName=function(){return"Chat"};a.ChatMessageModel.prototype.getAttachedFileURL=function(){var c=this.data.attachedFileURL;if(c)return c+=".img?apiKey\x3d"+a.User.AOMAPIKEY+"\x26system\x3d"+a.User.AOMSYS};a.ChatMessageModel.prototype.loadAttachedFile=
function(c){var b=this.getAttachedFileURL();if("undefined"==typeof b)throw new a.ApiomatRequestError(a.Status.ATTACHED_HREF_MISSING,200);return a.Datastore.getInstance().loadResource(b,c)};a.ChatMessageModel.prototype.postAttachedFile=function(c,b){var d={onOk:function(c){if(c)this.parent.data.attachedFileURL=c,this.parent.save({onOk:function(){a.Datastore.positiveCallback(b)},onError:function(d){a.Datastore.getInstance().deleteOnServer(c,{onOk:function(){a.Datastore.negativeCallback(b,d)},onError:function(c){a.Datastore.negativeCallback(b,
d)}});delete this.parent.data.attachedFileURL}});else{var d=new a.ApiomatRequestError(a.Status.HREF_NOT_FOUND);b?a.Datastore.negativeCallback(b,d):console&&console.log&&console.log("Error occured: "+d)}},onError:function(c){a.Datastore.negativeCallback(b,c)},parent:this};a.Datastore.getInstance().shouldSendOffline("POST")?a.Datastore.getInstance().sendOffline("POST",null,c,!1,d):a.Datastore.getInstance().postStaticDataOnServer(c,!1,d)};a.ChatMessageModel.prototype.deleteAttachedFile=function(c){var b=
this.data.attachedFileURL;delete this.data.attachedFileURL;this.save({onOk:function(){var d={onOk:function(){a.Datastore.positiveCallback(c)},onError:function(b){a.Datastore.negativeCallback(c,b)}};a.Datastore.getInstance().shouldSendOffline("DELETE")?a.Datastore.getInstance().sendOffline("DELETE",b,null,null,d):a.Datastore.getInstance().deleteOnServer(b,d)},onError:function(d){this.parent.data.attachedFileURL=b;a.Datastore.negativeCallback(c,d)},parent:this})};a.ChatMessageModel.prototype.getAttachedImageURL=
function(c,b,d,e,f){var g=this.data.attachedImageURL;if(g)return g+=".img?apiKey\x3d"+a.User.AOMAPIKEY+"\x26system\x3d"+a.User.AOMSYS,c&&(g+="\x26width\x3d"+c),b&&(g+="\x26height\x3d"+b),d&&(g+="\x26bgcolor\x3d"+d),e&&(g+="\x26alpha\x3d"+e),f&&(g+="\x26format\x3d"+f),g};a.ChatMessageModel.prototype.loadAttachedImage=function(c,b,d,e,f,g){c=this.getAttachedImageURL(c,b,d,e,f);if("undefined"==typeof c)throw new a.ApiomatRequestError(a.Status.ATTACHED_HREF_MISSING,200);return a.Datastore.getInstance().loadResource(c,
g)};a.ChatMessageModel.prototype.postAttachedImage=function(c,b){var d={onOk:function(c){if(c)this.parent.data.attachedImageURL=c,this.parent.save({onOk:function(){a.Datastore.positiveCallback(b)},onError:function(d){a.Datastore.getInstance().deleteOnServer(c,{onOk:function(){a.Datastore.negativeCallback(b,d)},onError:function(c){a.Datastore.negativeCallback(b,d)}});delete this.parent.data.attachedImageURL}});else{var d=new a.ApiomatRequestError(a.Status.HREF_NOT_FOUND);b?a.Datastore.negativeCallback(b,
d):console&&console.log&&console.log("Error occured: "+d)}},onError:function(c){a.Datastore.negativeCallback(b,c)},parent:this};a.Datastore.getInstance().shouldSendOffline("POST")?a.Datastore.getInstance().sendOffline("POST",null,c,!0,d):a.Datastore.getInstance().postStaticDataOnServer(c,!0,d)};a.ChatMessageModel.prototype.deleteAttachedImage=function(c){var b=this.data.attachedImageURL;delete this.data.attachedImageURL;this.save({onOk:function(){var d={onOk:function(){a.Datastore.positiveCallback(c)},
onError:function(b){a.Datastore.negativeCallback(c,b)}};a.Datastore.getInstance().shouldSendOffline("DELETE")?a.Datastore.getInstance().sendOffline("DELETE",b,null,null,d):a.Datastore.getInstance().deleteOnServer(b,d)},onError:function(d){this.parent.data.attachedImageURL=b;a.Datastore.negativeCallback(c,d)},parent:this})};a.ChatMessageModel.prototype.getSenderUserName=function(){return this.data.senderUserName};a.ChatMessageModel.prototype.setSenderUserName=function(a){this.data.senderUserName=a};
a.ChatMessageModel.prototype.getText=function(){return this.data.text};a.ChatMessageModel.prototype.setText=function(a){this.data.text=a};a.ChatMessageModel.prototype.send=function(c,b){var d=[];if(1<arguments.length)for(var e=0;e<arguments.length-1;e++)d.push(arguments[e]);a.Datastore.getInstance().updateOnServerWithJSON(this.getHref()+"/method/send",JSON.stringify(d),b)}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.ConversationModel={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.ConversationModel=function(){this.init();this.getMessages=function(){return this.messages};this.loadMessages=function(c,b){var d=this.data.messagesHref;if("undefined"==typeof d)throw new a.ApiomatRequestError(a.Status.ATTACHED_HREF_MISSING,200);var e={onOk:function(c){this.parent.messages=c;a.Datastore.positiveCallback(b,c)},onError:function(c){204==c.statusCode&&(this.parent.messages=null);a.Datastore.negativeCallback(b,c)},parent:this};a.Datastore.getInstance().loadFromServer(d,e,
void 0,!1,c,a.ChatMessageModel)};this.loadMessagesAndRefHref=function(c,b){var d=this.data.messagesHref;if("undefined"==typeof d)throw new a.ApiomatRequestError(a.Status.ATTACHED_HREF_MISSING,200);var e={onOk:function(c){this.parent.messages=c;a.Datastore.positiveCallback(b,c)},onError:function(c){a.Datastore.negativeCallback(b,c)},parent:this};a.Datastore.getInstance().loadFromServer(d,e,void 0,!0,c,a.ChatMessageModel)};this.postMessages=function(c,b){if(!1==c||"undefined"===typeof c.getHref()){var d=
new a.ApiomatRequestError(a.Status.SAVE_REFERENECE_BEFORE_REFERENCING);b?a.Datastore.negativeCallback(b,d):console&&console.log&&console.log("Error occured: "+d)}else d={onOk:function(d){d&&1>this.parent.messages.filter(function(a){return a.getHref()&&d&&a.getHref()===d}).length&&this.parent.messages.push(c);a.Datastore.positiveCallback(b,d)},onError:function(c){a.Datastore.negativeCallback(b,c)},parent:this},a.Datastore.getInstance().shouldSendOffline("POST")?a.Datastore.getInstance().sendOffline("POST",
this.getHref(),c,"messages",d):a.Datastore.getInstance().postOnServer(c,d,this.data.messagesHref)};this.removeMessages=function(c,b){var d=c.getHref().substring(c.getHref().lastIndexOf("/")+1),d=this.data.messagesHref+"/"+d,e={onOk:function(d){d=-1;if("undefined"!=typeof this.parent.messages&&"undefined"!=typeof this.parent.messages.length&&0<this.parent.messages.length)for(var e=0;e<this.parent.messages.length;e++)if(this.parent.messages[e].data.href===c.data.href){d=e;break}-1!=d&&this.parent.messages.splice(d,
1);a.Datastore.positiveCallback(b)},onError:function(c){a.Datastore.negativeCallback(b,c)},parent:this};a.Datastore.getInstance().deleteOnServer(d,e)};this.getMessagesCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(this.getHref(),"messages",c,b)}};a.ConversationModel.getConversationModels=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.ConversationModel,c,b,!1)};a.ConversationModel.getConversationModelsAndRefHref=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.ConversationModel,
c,b,d)};a.ConversationModel.getConversationModelsCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.ConversationModel,void 0,c,b)};a.ConversationModel.prototype=new a.AbstractClientDataModel;a.ConversationModel.prototype.constructor=a.ConversationModel;a.ConversationModel.prototype.init=function(){this.data={};this.messages=[]};a.ConversationModel.prototype.getSimpleName=function(){return"ConversationModel"};a.ConversationModel.prototype.getModuleName=function(){return"Chat"};a.ConversationModel.prototype.getAttendeeUserNames=
function(){return this.data.attendeeUserNames};a.ConversationModel.prototype.setAttendeeUserNames=function(a){this.data.attendeeUserNames=a};a.ConversationModel.prototype.getMessages=function(){return this.data.messages};a.ConversationModel.prototype.setMessages=function(a){this.data.messages=a};a.ConversationModel.prototype.getSubject=function(){return this.data.subject};a.ConversationModel.prototype.setSubject=function(a){this.data.subject=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Module={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Module=function(){this.init()};a.Module.getModules=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.Module,c,b,!1)};a.Module.getModulesAndRefHref=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.Module,c,b,d)};a.Module.getModulesCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.Module,void 0,c,b)};a.Module.prototype=new a.AbstractClientDataModel;a.Module.prototype.constructor=a.Module;a.Module.prototype.init=function(){this.data=
{}};a.Module.prototype.getSimpleName=function(){return"Module"};a.Module.prototype.getModuleName=function(){return"LearnCenterMain"};a.Module.prototype.getDescription=function(){return this.data.description};a.Module.prototype.setDescription=function(a){this.data.description=a};a.Module.prototype.getEmail_id=function(){return this.data.email_id};a.Module.prototype.setEmail_id=function(a){this.data.email_id=a};a.Module.prototype.getFile=function(){return this.data.file};a.Module.prototype.setFile=
function(a){this.data.file=a};a.Module.prototype.getName=function(){return this.data.name};a.Module.prototype.setName=function(a){this.data.name=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Student={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Student=function(){this.init()};a.Student.getStudents=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.Student,c,b,!1)};a.Student.getStudentsAndRefHref=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.Student,c,b,d)};a.Student.getStudentsCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.Student,void 0,c,b)};a.Student.prototype=new a.AbstractClientDataModel;a.Student.prototype.constructor=a.Student;a.Student.prototype.init=
function(){this.data={}};a.Student.prototype.getSimpleName=function(){return"Student"};a.Student.prototype.getModuleName=function(){return"LearnCenterMain"};a.Student.prototype.getContact_address=function(){return this.data.contact_address};a.Student.prototype.setContact_address=function(a){this.data.contact_address=a};a.Student.prototype.getEducation=function(){return this.data.education};a.Student.prototype.setEducation=function(a){this.data.education=a};a.Student.prototype.getEmail=function(){return this.data.email};
a.Student.prototype.setEmail=function(a){this.data.email=a};a.Student.prototype.getFollow=function(){return this.data.follow};a.Student.prototype.setFollow=function(a){this.data.follow=a};a.Student.prototype.getName=function(){return this.data.name};a.Student.prototype.setName=function(a){this.data.name=a};a.Student.prototype.getPassword=function(){return this.data.password};a.Student.prototype.setPassword=function(a){this.data.password=a};a.Student.prototype.getPhoto=function(){return this.data.photo};
a.Student.prototype.setPhoto=function(a){this.data.photo=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Courses={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Courses=function(){this.init()};a.Courses.getCoursess=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.Courses,c,b,!1)};a.Courses.getCoursessAndRefHref=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.Courses,c,b,d)};a.Courses.getCoursessCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.Courses,void 0,c,b)};a.Courses.prototype=new a.AbstractClientDataModel;a.Courses.prototype.constructor=a.Courses;a.Courses.prototype.init=
function(){this.data={}};a.Courses.prototype.getSimpleName=function(){return"Courses"};a.Courses.prototype.getModuleName=function(){return"LearnCenterMain"};a.Courses.prototype.getCourses_date=function(){return this.data.courses_date};a.Courses.prototype.setCourses_date=function(a){this.data.courses_date=a};a.Courses.prototype.getCourses_description=function(){return this.data.courses_description};a.Courses.prototype.setCourses_description=function(a){this.data.courses_description=a};a.Courses.prototype.getCourses_name=
function(){return this.data.courses_name};a.Courses.prototype.setCourses_name=function(a){this.data.courses_name=a};a.Courses.prototype.getCourses_teacher=function(){return this.data.courses_teacher};a.Courses.prototype.setCourses_teacher=function(a){this.data.courses_teacher=a};a.Courses.prototype.getCourses_time=function(){return this.data.courses_time};a.Courses.prototype.setCourses_time=function(a){this.data.courses_time=a};a.Courses.prototype.getTeacher_id=function(){return this.data.teacher_id};
a.Courses.prototype.setTeacher_id=function(a){this.data.teacher_id=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Teacher={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Teacher=function(){this.init()};a.Teacher.getTeachers=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.Teacher,c,b,!1)};a.Teacher.getTeachersAndRefHref=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.Teacher,c,b,d)};a.Teacher.getTeachersCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.Teacher,void 0,c,b)};a.Teacher.prototype=new a.AbstractClientDataModel;a.Teacher.prototype.constructor=a.Teacher;a.Teacher.prototype.init=
function(){this.data={}};a.Teacher.prototype.getSimpleName=function(){return"Teacher"};a.Teacher.prototype.getModuleName=function(){return"LearnCenterMain"};a.Teacher.prototype.getContact_address=function(){return this.data.contact_address};a.Teacher.prototype.setContact_address=function(a){this.data.contact_address=a};a.Teacher.prototype.getEducation_background=function(){return this.data.education_background};a.Teacher.prototype.setEducation_background=function(a){this.data.education_background=
a};a.Teacher.prototype.getEmail=function(){return this.data.email};a.Teacher.prototype.setEmail=function(a){this.data.email=a};a.Teacher.prototype.getName=function(){return this.data.name};a.Teacher.prototype.setName=function(a){this.data.name=a};a.Teacher.prototype.getPassword=function(){return this.data.password};a.Teacher.prototype.setPassword=function(a){this.data.password=a};a.Teacher.prototype.getPhone=function(){return this.data.phone};a.Teacher.prototype.setPhone=function(a){this.data.phone=
a};a.Teacher.prototype.getPhoto=function(){return this.data.photo};a.Teacher.prototype.setPhoto=function(a){this.data.photo=a};a.Teacher.prototype.getRtc_code=function(){return this.data.rtc_code};a.Teacher.prototype.setRtc_code=function(a){this.data.rtc_code=a};a.Teacher.prototype.getStudy=function(){return this.data.study};a.Teacher.prototype.setStudy=function(a){this.data.study=a};a.Teacher.prototype.getTeaching_experiences=function(){return this.data.teaching_experiences};a.Teacher.prototype.setTeaching_experiences=
function(a){this.data.teaching_experiences=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.AOMOfflineInfo={},Apiomat.AOMOfflineHandler={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.AOMOfflineInfo=function(a,b,d,e,f,g,t){this.httpMethod=a;this.fileKey=d;this.timestamp=e;this.url=b;this.clazz=e;this.localId=f;this.refName=g;this.isStaticData=t};a.AOMOfflineHandler=function(){a.AOMOfflineHandler.AOMTASKEVENT="AomTaskEvent";var c=[],b={},d={},e=[],f=new a.AOMFileHandler;a.AOMHelper.isTitaniumApp()&&(f=new a.AOMFileHandlerTi);a.AOMHelper.addEventListener(a.AOMNetworkHandler.AOMNETWORKEVENT,function(a){t()});var g=function(a,b,c,d){f.readFile(a,function(a){a&&JSON.parse(a);
c&&c()},function(b){console.error("Error on restoring content of "+a+" --\x3e "+b.code);d&&d(b)})},t=function(){if(1>c.length)b={},u();else if(!1!==a.AOMNetworkHandler.isConnected()){var d=c.shift();delete e[d.localId];v();f.readFile(d.fileKey,function(a){f.removeFile(d.fileKey);if(a&&!1===d.isStaticData){var b=new d.clazz;b.fromJson(a);a=b}(a||d.isStaticData&&d.url)&&w(d,a,d.isStaticData)},function(a){console.error("Error occured on reading file "+a)})}},k={extCallback:void 0,onOk:function(a){if(k.extCallback&&
k.extCallback.onOk)k.extCallback.onOk(a);t()},onError:function(a){if(k.extCallback&&k.extCallback.onError)k.extCallback.onError(a);t()}},w=function(c,e,f){var g=c.url,n=void 0!=c.refName&&0<c.refName.length;switch(c.httpMethod){case "POST":n&&!1===f&&(g=g.substring(g.lastIndexOf("/")+1),r(e),g=b[g]+"/"+c.refName);k.extCallback={onOk:function(e){if(null!=e&&0<e.length){b[c.localId]=e;u();if(!1===f){var g=c.localId;if((model=d[g])&&model.isOffline())delete d[g],model.data.href=e,model.setOffline(!1)}a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,
{wasSuccess:!0,info:c,href:e})}},onError:function(b){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:b,info:c,href:h})}};g?f?a.Datastore.getInstance().postStaticDataOnServerWithHref(e,g,k):a.Datastore.getInstance().postOnServer(e,k,g):a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:error,info:c,href:h});break;case "PUT":var h=r(e);void 0!==h&&0<h.length?(k.extCallback={onOk:function(){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,
{wasSuccess:!0,info:c})},onError:function(b){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:b,info:c})}},a.Datastore.getInstance().updateOnServer(e,k)):a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:a.Status.HREF_NOT_FOUND,info:c});break;case "DELETE":h=void 0,h=f?p(g):r(e),n&&(g=g.substring(g.lastIndexOf("/")+1),h=b[g]+"/"+c.refName+"/"+h.substring(h.lastIndexOf("/")+1)),h&&0<h.length?(k.extCallback={onOk:function(){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,
{wasSuccess:!0,info:c})},onError:function(b){a.AOMHelper.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:b,info:c})}},n||f?a.Datastore.getInstance().deleteOnServer(h,k):a.Datastore.getInstance().deleteModelOnServer(e,k)):a.sendEvent(a.AOMOfflineHandler.AOMTASKEVENT,{wasSuccess:!1,reason:a.Status.HREF_NOT_FOUND,info:c})}},x=function(){for(var b=0,c=Math.floor(1E6*Math.random()+1);e[c]&&5>b;)b++,c=Math.floor(1E6*Math.random()+1);if(4<=b)throw new a.ApiomatRequestError(a.Status.TOO_MANY_LOCALIDS);
return c},r=function(a){var c=a.getHref();if(a.isOffline()){var d=a.getID();if(void 0!==d&&0<d.length&&(d=b[d]))c=d,a.data.href=c;for(var e in a.data)e.endsWith("URL")&&(d=p(a.data[e]))&&(a.data[e]=d)}return c},p=function(a){a=a.substring(a.lastIndexOf("/")+1);return b[a]},u=function(){return f.writeFile(a.AOMFileHandler.HREFMAP_FILENAME,JSON.stringify(b))},v=function(){f.writeFile(a.AOMFileHandler.USEDLOCALIDS_FILENAME,JSON.stringify(e));f.writeFile(a.AOMFileHandler.TASKLIST_FILENAME,JSON.stringify(c))},
n=function(b,c,d,e){var g=void 0;f.getSizeOfAppDir(function(h){h&&h>=1024*this.cacheSizeInMB?(console.error("Max cache size is reached. Can't add to cache!"),e&&e(new a.ApiomatRequestError(a.Status.MAX_CACHE_SIZE_REACHED))):(g=f.createFileName(c),f.writeFile(g,b||"",function(){d&&d(g)},function(b){console.error("Can't persist to cache: "+b.code);e&&e(new a.ApiomatRequestError(a.Status.CANT_WRITE_IN_CACHE))}))})};this.cacheSizeInMB=4;this.addTask=function(b,e,f,g,k,h){var q=e,p=!1===f instanceof a.AbstractClientDataModel,
t=f;!1===p&&(t=f.toJson());var r=void 0;if("POST"===b){try{r=x()}catch(u){throw u;}q+="/"+(g?g+"/":"")+r;!1===p&&(d[r]=f)}n(t,r||b,function(d){d&&(d=new a.AOMOfflineInfo(b,e,d,f?f.constructor:void 0,r,g,p),c.push(d),v());k&&k(q)},function(a){console.error("Got error on adding task to offline queue: "+a);h&&h(a)})};this.init=function(d,f){var k=function(){g(a.AOMFileHandler.USEDLOCALIDS_FILENAME,e,function(){t();"undefined"!==typeof d&&d()},function(a){"undefined"!==typeof f&&f(a)})},n=function(){g(a.AOMFileHandler.HREFMAP_FILENAME,
b,function(){k()},function(a){k()})};g(a.AOMFileHandler.TASKLIST_FILENAME,c,function(){n()},function(a){n()})};this.isConnected=function(){return a.AOMNetworkHandler.isConnected()};this.clearCache=function(){b={};u();for(var a=0,e=c.length;a<e;a++){var g=c[a];g.fileKey&&f.removeFile(g.fileKey)}d={};c=[];v()}}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.User={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.User=function(c,b){this.init();"undefined"!==typeof c&&this.setUserName(c);"undefined"!==typeof b&&this.setPassword(b);this.initDatastoreIfNeeded=function(b){if(!1===a.Datastore.isInstantiated())if("undefined"!==typeof this.getUserName()&&"undefined"!==typeof this.getPassword())a.Datastore.configureWithCredentials(this);else if("getSessionToken"in this&&"undefined"!==typeof this.getSessionToken()&&this.getSessionToken())a.Datastore.configureWithUserSessionToken(this);else if("undefined"!==
typeof b&&b)a.Datastore.configurePlain(a.User.AOMBASEURL,a.User.AOMAPIKEY,a.User.AOMSYS);else throw Error("The Datastore needs to be configured with user credentials or a session token for this method to work.");};this.save=function(b,c){this.initDatastoreIfNeeded(!1);a.AbstractClientDataModel.prototype.save.apply(this,[b,c])};this.requestNewPassword=function(){a.Datastore.getInstance().postOnServer(this,{onOk:function(a){},onError:function(a){}},"models/requestResetPassword/")};this.resetPassword=
function(b,c){if(this.getCurrentState==a.ObjectState.PERSISTING)a.Datastore.negativeCallback(c,error);else{var f={onOk:function(){this.parent.setOffline(this.wasLocalSave||!1);a.Datastore.configure(this.parent);a.Datastore.positiveCallback(c)},onError:function(b){a.Datastore.negativeCallback(c,b)},parent:this};this.setPassword(b);a.Datastore.getInstance().shouldSendOffline("PUT")?(f.wasLocalSave=!0,a.Datastore.getInstance().sendOffline("PUT",this.getHref(),this,void 0,f)):a.Datastore.getInstance().updateOnServer(this,
f)}};this.requestSessionToken=function(a,b){this.requestSessionTokenWithRefreshToken(void 0,a,b)};this.requestSessionTokenWithRefreshToken=function(b,c,f){b=b||void 0;this.initDatastoreIfNeeded("undefined"===b?!1:!0);var g=f;"undefined"!==typeof c&&c&&(g={onOk:function(b){var c=b.sessionToken||"";""===c?a.Datastore.negativeCallback(f,new a.ApiomatRequestError(a.Status.NO_TOKEN_RECEIVED,200)):(this.parent.setSessionToken(c),a.Datastore.configureWithUserSessionToken(this.parent),a.Datastore.positiveCallback(f,
b))},onError:function(b){a.Datastore.negativeCallback(f,b)},parent:this});"undefined"===typeof b?a.Datastore.getInstance().requestSessionToken(g):a.Datastore.getInstance().requestSessionTokenWithRefreshToken(b,g)}};a.User.AOMBASEURL="https://apiomat.org/yambas/rest/apps/LearnCenter";a.User.AOMAPIKEY="7026910685787932036";a.User.AOMSYS="LIVE";a.User.AOMSDKVERSION="2.0.0-2518";a.User.getUsers=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.User,c,b,!1)};a.User.getUsersAndRefHref=
function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.User,c,b,d)};a.User.getUsersCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.User,void 0,c,b)};a.User.prototype=new a.AbstractClientDataModel;a.User.prototype.constructor=a.User;a.User.prototype.loadMe=function(c){this.initDatastoreIfNeeded(!1);a.Datastore.getInstance().loadFromServer("models/me",c,this,!1)};a.User.prototype.init=function(){this.data={};this.data.dynamicAttributes={}};a.User.prototype.getSimpleName=
function(){return"User"};a.User.prototype.getModuleName=function(){return"Basics"};a.User.prototype.getAge=function(){return this.data.dynamicAttributes.age};a.User.prototype.setAge=function(a){this.data.dynamicAttributes.age=a};a.User.prototype.getCompany=function(){return this.data.dynamicAttributes.company};a.User.prototype.setCompany=function(a){this.data.dynamicAttributes.company=a};a.User.prototype.getDateOfBirth=function(){var a=this.data.dateOfBirth;return"undefined"!=typeof a?new Date(a):
void 0};a.User.prototype.setDateOfBirth=function(a){this.data.dateOfBirth=a.getTime()};a.User.prototype.getFirstName=function(){return this.data.firstName};a.User.prototype.setFirstName=function(a){this.data.firstName=a};a.User.prototype.getImageURL=function(c,b,d,e,f){var g=this.data.dynamicAttributes.imageURL;if(g)return g+=".img?apiKey\x3d"+a.User.AOMAPIKEY+"\x26system\x3d"+a.User.AOMSYS,c&&(g+="\x26width\x3d"+c),b&&(g+="\x26height\x3d"+b),d&&(g+="\x26bgcolor\x3d"+d),e&&(g+="\x26alpha\x3d"+e),
f&&(g+="\x26format\x3d"+f),g};a.User.prototype.loadImage=function(c,b,d,e,f,g){c=this.getImageURL(c,b,d,e,f);if("undefined"==typeof c)throw new a.ApiomatRequestError(a.Status.ATTACHED_HREF_MISSING,200);return a.Datastore.getInstance().loadResource(c,g)};a.User.prototype.postImage=function(c,b){var d={onOk:function(c){if(c)this.parent.data.dynamicAttributes.imageURL=c,this.parent.save({onOk:function(){a.Datastore.positiveCallback(b)},onError:function(d){a.Datastore.getInstance().deleteOnServer(c,{onOk:function(){a.Datastore.negativeCallback(b,
d)},onError:function(c){a.Datastore.negativeCallback(b,d)}});delete this.parent.data.dynamicAttributes.imageURL}});else{var d=new a.ApiomatRequestError(a.Status.HREF_NOT_FOUND);b?a.Datastore.negativeCallback(b,d):console&&console.log&&console.log("Error occured: "+d)}},onError:function(c){a.Datastore.negativeCallback(b,c)},parent:this};a.Datastore.getInstance().shouldSendOffline("POST")?a.Datastore.getInstance().sendOffline("POST",null,c,!0,d):a.Datastore.getInstance().postStaticDataOnServer(c,!0,
d)};a.User.prototype.deleteImage=function(c){var b=this.data.dynamicAttributes.imageURL;delete this.data.dynamicAttributes.imageURL;this.save({onOk:function(){var d={onOk:function(){a.Datastore.positiveCallback(c)},onError:function(b){a.Datastore.negativeCallback(c,b)}};a.Datastore.getInstance().shouldSendOffline("DELETE")?a.Datastore.getInstance().sendOffline("DELETE",b,null,null,d):a.Datastore.getInstance().deleteOnServer(b,d)},onError:function(d){this.parent.data.dynamicAttributes.imageURL=b;a.Datastore.negativeCallback(c,
d)},parent:this})};a.User.prototype.getLastName=function(){return this.data.lastName};a.User.prototype.setLastName=function(a){this.data.lastName=a};a.User.prototype.getLocLatitude=function(){var a=this.data.loc;if(a)return a[0]};a.User.prototype.getLocLongitude=function(){var a=this.data.loc;if(a)return a[1]};a.User.prototype.setLocLatitude=function(a){var b=this.data.loc;b?b[0]=a:b=[a,void 0];this.data.loc=b};a.User.prototype.setLocLongitude=function(a){var b=this.data.loc;b?b[1]=a:b=[0,a];this.data.loc=
b};a.User.prototype.getPassword=function(){return this.data.password};a.User.prototype.setPassword=function(a){this.data.password=a};a.User.prototype.getProfession=function(){return this.data.dynamicAttributes.profession};a.User.prototype.setProfession=function(a){this.data.dynamicAttributes.profession=a};a.User.prototype.getSessionToken=function(){return this.data.sessionToken};a.User.prototype.setSessionToken=function(a){this.data.sessionToken=a};a.User.prototype.getSex=function(){return this.data.dynamicAttributes.sex};
a.User.prototype.setSex=function(a){this.data.dynamicAttributes.sex=a};a.User.prototype.getUserName=function(){return this.data.userName};a.User.prototype.setUserName=function(a){this.data.userName=a}})("undefined"===typeof exports?Apiomat:exports);"undefined"!==typeof goog&&(Apiomat.Role={});"undefined"===typeof exports&&(Apiomat=Apiomat||{});
(function(a){a.Role=function(){this.init()};a.Role.getRoles=function(c,b){a.Datastore.getInstance().loadListFromServerWithClass(a.Role,c,b,!1)};a.Role.getRolesAndRefHref=function(c,b,d){a.Datastore.getInstance().loadListFromServerWithClass(a.Role,c,b,d)};a.Role.getRolesCount=function(c,b){a.Datastore.getInstance().loadCountFromServer(a.Role,void 0,c,b)};a.Role.prototype=new a.AbstractClientDataModel;a.Role.prototype.constructor=a.Role;a.Role.prototype.init=function(){this.data={}};a.Role.prototype.getSimpleName=
function(){return"Role"};a.Role.prototype.getModuleName=function(){return"Basics"};a.Role.prototype.getMembers=function(){return this.data.members};a.Role.prototype.setMembers=function(a){this.data.members=a};a.Role.prototype.getName=function(){return this.data.name};a.Role.prototype.setName=function(a){this.data.name=a}})("undefined"===typeof exports?Apiomat:exports);